// Styles for the lead-detail screen. Extracted from [id].tsx so the screen
// stays focused on data flow + handlers, and helper components (CadenceStrip,
// DetailField) can share the same StyleSheet without prop-drilling.

import { colors, type Palette } from "@trendywheels/ui-tokens";
import { StyleSheet } from "react-native";

export function makeStyles(palette: Palette) {
  return StyleSheet.create({
    root: { flex: 1, backgroundColor: palette.bg },
    topBar: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 16,
      paddingBottom: 12,
      backgroundColor: palette.bg,
      borderBottomWidth: 1,
      borderBottomColor: palette.border,
    },
    topBarTitle: {
      color: palette.text,
      fontSize: 17,
      fontWeight: "700",
      flex: 1,
      textAlign: "center",
      marginHorizontal: 12,
    },
    heroCard: {
      margin: 14,
      backgroundColor: palette.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: palette.border,
      padding: 14,
      gap: 12,
    },
    heroTop: { flexDirection: "row", alignItems: "flex-start", gap: 12 },
    name: { color: palette.text, fontSize: 22, fontWeight: "800" },
    subline: { color: palette.muted, fontSize: 12, marginTop: 2 },
    assigned: { color: colors.brand.friendlyBlue, fontSize: 11, fontWeight: "700", marginTop: 4 },
    unassigned: { color: "#F5B800", fontSize: 11, fontWeight: "700", marginTop: 4 },
    value: { color: colors.brand.trendyPink, fontWeight: "800", fontSize: 16 },
    stageChip: {
      marginTop: 6,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 999,
      backgroundColor: colors.brand.trendyPink + "22",
    },
    stageChipText: {
      color: colors.brand.trendyPink,
      fontSize: 10,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 0.5,
    },
    actionsRow: { flexDirection: "row", gap: 8 },
    cadenceRow: { flexDirection: "row", gap: 6, marginTop: 6 },
    cadenceChip: {
      flex: 1,
      paddingHorizontal: 8,
      paddingVertical: 6,
      borderRadius: 8,
      alignItems: "center",
    },
    cadenceChipLabel: {
      fontSize: 9,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 0.5,
    },
    cadenceChipValue: { color: palette.text, fontSize: 12, fontWeight: "700", marginTop: 1 },
    actionBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 999,
    },
    actionBtnText: { color: "#fff", fontWeight: "800", fontSize: 11 },
    tabRow: {
      flexDirection: "row",
      paddingHorizontal: 14,
      gap: 6,
      marginBottom: 4,
    },
    tab: {
      flex: 1,
      paddingVertical: 10,
      borderRadius: 10,
      backgroundColor: palette.card,
      borderWidth: 1,
      borderColor: palette.border,
      alignItems: "center",
    },
    tabActive: { backgroundColor: colors.brand.trendyPink, borderColor: colors.brand.trendyPink },
    tabText: {
      color: palette.muted,
      fontSize: 12,
      fontWeight: "800",
      textTransform: "uppercase",
    },
    tabTextActive: { color: "#fff" },
    card: {
      backgroundColor: palette.card,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: palette.border,
      padding: 12,
      gap: 8,
    },
    sectionTitle: { color: palette.muted, fontSize: 11, fontWeight: "700", letterSpacing: 1 },
    stageRow: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
    stage: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 999,
      backgroundColor: palette.bg,
      borderWidth: 1,
      borderColor: palette.border,
    },
    stageText: {
      color: palette.muted,
      fontSize: 11,
      fontWeight: "700",
      textTransform: "capitalize",
    },
    noteInput: {
      backgroundColor: palette.bg,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: palette.border,
      padding: 10,
      color: palette.text,
      fontSize: 14,
      minHeight: 80,
      textAlignVertical: "top",
    },
    logBtn: {
      backgroundColor: colors.brand.trendyPink,
      borderRadius: 10,
      paddingVertical: 10,
      alignItems: "center",
    },
    logBtnText: { color: "#fff", fontWeight: "800" },
    activityRow: { flexDirection: "row", gap: 10, paddingVertical: 8 },
    activityDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: colors.brand.trendyPink,
      marginTop: 6,
    },
    activityType: {
      color: palette.text,
      fontSize: 13,
      fontWeight: "700",
      textTransform: "capitalize",
    },
    activityNote: { color: palette.muted, fontSize: 12, marginTop: 2 },
    activityDate: { color: palette.muted, fontSize: 10, marginTop: 4 },
    empty: { alignItems: "center", paddingVertical: 30, gap: 6 },
    emptyText: { color: palette.muted, fontSize: 12 },
    vehicleRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      backgroundColor: palette.card,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: palette.border,
      padding: 10,
    },
    vehicleName: { color: palette.text, fontSize: 13, fontWeight: "700" },
    attachBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
      backgroundColor: colors.brand.friendlyBlue,
      paddingVertical: 12,
      borderRadius: 10,
    },
    attachBtnText: { color: "#fff", fontWeight: "800", fontSize: 13 },
    modalBg: { flex: 1, backgroundColor: "rgba(0,0,0,0.5)", justifyContent: "flex-end" },
    modal: {
      backgroundColor: palette.bg,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      padding: 20,
      paddingBottom: 40,
      maxHeight: "70%",
    },
    modalTitle: { color: palette.text, fontSize: 18, fontWeight: "700", marginBottom: 12 },
    modalSearch: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      backgroundColor: palette.bg,
      borderWidth: 1,
      borderColor: palette.border,
      borderRadius: 10,
      paddingHorizontal: 10,
      height: 40,
      marginBottom: 10,
    },
    modalSearchInput: { flex: 1, color: palette.text, fontSize: 14, paddingVertical: 0 },
    vehiclePickerRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: palette.border,
    },
    vName: { color: palette.text, fontSize: 14, fontWeight: "700" },
    vMeta: { color: palette.muted, fontSize: 11 },
  });
}
