module.exports = {
  apps: [
    {
      name: "trendywheels-api",
      cwd: "./apps/api",
      script: "pnpm",
      args: "exec tsx src/server.ts",
      interpreter: "none",
      instances: 1,
      exec_mode: "fork",
      env_production: {
        NODE_ENV: "production",
        PORT: 4000,
      },
      max_memory_restart: "500M",
      error_file: "/var/log/trendywheels/api-error.log",
      out_file: "/var/log/trendywheels/api-out.log",
      merge_logs: true,
    },
    {
      name: "trendywheels-workers",
      cwd: "./apps/api",
      script: "pnpm",
      args: "exec tsx src/workers/index.ts",
      interpreter: "none",
      instances: 1,
      exec_mode: "fork",
      env_production: {
        NODE_ENV: "production",
      },
      max_memory_restart: "500M",
      error_file: "/var/log/trendywheels/workers-error.log",
      out_file: "/var/log/trendywheels/workers-out.log",
      merge_logs: true,
    },
    {
      name: "trendywheels-admin",
      cwd: "./apps/admin",
      script: "pnpm",
      args: "exec next start --port 3001 --hostname 0.0.0.0",
      interpreter: "none",
      instances: 1,
      exec_mode: "fork",
      env_production: {
        NODE_ENV: "production",
      },
      max_memory_restart: "500M",
      error_file: "/var/log/trendywheels/admin-error.log",
      out_file: "/var/log/trendywheels/admin-out.log",
      merge_logs: true,
    },
    {
      name: "trendywheels-support",
      cwd: "./apps/support",
      script: "pnpm",
      args: "exec next start --port 3002 --hostname 0.0.0.0",
      interpreter: "none",
      instances: 1,
      exec_mode: "fork",
      env_production: {
        NODE_ENV: "production",
      },
      max_memory_restart: "500M",
      error_file: "/var/log/trendywheels/support-error.log",
      out_file: "/var/log/trendywheels/support-out.log",
      merge_logs: true,
    },
    {
      name: "trendywheels-inventory",
      cwd: "./apps/inventory",
      script: "pnpm",
      args: "exec next start --port 3003 --hostname 0.0.0.0",
      interpreter: "none",
      instances: 1,
      exec_mode: "fork",
      env_production: {
        NODE_ENV: "production",
      },
      max_memory_restart: "500M",
      error_file: "/var/log/trendywheels/inventory-error.log",
      out_file: "/var/log/trendywheels/inventory-out.log",
      merge_logs: true,
    },
    {
      name: "trendywheels-customer",
      cwd: "./apps/customer",
      script: "pnpm",
      args: "exec next start --port 3004 --hostname 0.0.0.0",
      interpreter: "none",
      instances: 1,
      exec_mode: "fork",
      env_production: {
        NODE_ENV: "production",
      },
      max_memory_restart: "500M",
      error_file: "/var/log/trendywheels/customer-error.log",
      out_file: "/var/log/trendywheels/customer-out.log",
      merge_logs: true,
    },
  ],
};
